"""
app/engine/risk.py

DEPRECATED — the independent WBGT-tier + Heat-Index-tier risk classification
has been removed from the active pipeline.

There is exactly ONE authoritative final risk_level: it comes from HTSI
(computed in main.py via calculate_htsi() → classify_risk() in htsi.py).

WBGT proxy and raw Heat Index are returned as supporting_metrics only;
they do NOT independently produce a risk_level.

The three functions below are retained only because test_risk_engine.py
still imports them.  They are NOT called from main.py.
"""


def calculate_risk_category(wbgt: float, heat_index: float) -> str:
    """
    DEPRECATED — not used in the active pipeline.

    Retained only so test_risk_engine.py imports do not break.
    The authoritative risk_level is derived from HTSI, not WBGT/HI tiers.

    WBGT Thresholds (ACGIH/Military):
    < 27.7 (Low), 27.7-29.4 (Moderate), 29.4-32.2 (High), >= 32.2 (Extreme)

    Heat Index Thresholds (NOAA):
    < 32.0 (Low), 32.0-39.0 (Moderate), 39.0-51.0 (High), >= 51.0 (Extreme)
    """
    wbgt_tier = 0
    if wbgt >= 32.2:
        wbgt_tier = 3
    elif wbgt >= 29.4:
        wbgt_tier = 2
    elif wbgt >= 27.7:
        wbgt_tier = 1

    hi_tier = 0
    if heat_index >= 51.0:
        hi_tier = 3
    elif heat_index >= 39.0:
        hi_tier = 2
    elif heat_index >= 32.0:
        hi_tier = 1

    max_tier = max(wbgt_tier, hi_tier)
    tiers = {0: "Low", 1: "Moderate", 2: "High", 3: "Extreme"}
    return tiers[max_tier]


def generate_risk_drivers(wbgt: float, heat_index: float, lst_anomaly: float, rh: float) -> list[str]:
    """
    DEPRECATED — not used in the active pipeline.

    Retained only so test_risk_engine.py imports do not break.
    The authoritative risk contributing factors are generated by
    htsi.generate_risk_drivers() in the new pipeline.
    """
    drivers = []
    if rh > 75.0:
        drivers.append("High humidity severely limiting sweat evaporation")
    if lst_anomaly >= 1.5:
        drivers.append("Severe Urban Heat Island effect amplifying local temperature")
    if wbgt >= 29.4:
        drivers.append("Dangerous wet-bulb globe temperature for outdoor labor")
    if heat_index >= 39.0:
        drivers.append("High risk of heat exhaustion or heatstroke")
    return drivers


def compute_ward_risk(wbgt: float, heat_index: float, lst_anomaly: float, rh: float) -> dict:
    """
    DEPRECATED — not used in the active pipeline.

    Retained only so test_risk_engine.py imports do not break.
    Returns dict: {"risk_category": str, "primary_drivers": list[str]}
    """
    category = calculate_risk_category(wbgt, heat_index)
    drivers = generate_risk_drivers(wbgt, heat_index, lst_anomaly, rh)
    return {
        "risk_category": category,
        "primary_drivers": drivers,
    }
